/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_vibe_pack_vibePack_diff_parameter_0$schema = z.string()
const dsh_vibe_pack_vibePack_diff_result$schema = z.array(z.object({
  'type': z.union([z.literal("create"), z.literal("update"), z.literal("delete"), z.literal("unchanged")]),
  'path': z.string(),
  'before': z.union([z.undefined(), z.object({
  'path': z.string(),
  'digest': z.string(),
  'owner': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
  'after': z.union([z.undefined(), z.object({
  'path': z.string(),
  'digest': z.string(),
  'owner': z.union([z.undefined(), z.string()]).optional(),
})]).optional(),
}))
const dsh_vibe_pack_vibePack_export_parameter_0$schema = z.string()
const dsh_vibe_pack_vibePack_export_result$schema = z.string()
const dsh_vibe_pack_vibePack_history_result$schema = z.object({
  'version': z.literal(1),
  'packs': z.record(z.string(), z.object({
  'version': z.string(),
  'sourceDigest': z.string(),
  'files': z.record(z.string(), z.string()),
  'checkpoint': z.object({
  'version': z.literal(1),
  'createdAt': z.string(),
  'files': z.array(z.object({
  'path': z.string(),
  'digest': z.string(),
  'owner': z.union([z.undefined(), z.string()]).optional(),
})),
  'ownership': z.record(z.string(), z.array(z.string())),
}),
})),
})
const dsh_vibe_pack_vibePack_installPack_parameter_0$schema = z.union([z.object({
  'kind': z.literal("directory"),
  'path': z.string(),
}), z.object({
  'kind': z.literal("archive"),
  'path': z.string(),
})])
const dsh_vibe_pack_vibePack_installPack_parameter_1$schema = z.boolean()
const dsh_vibe_pack_vibePack_installPack_parameter_2$schema = z.string()
const dsh_vibe_pack_vibePack_installPack_result$schema = z.object({
  'pack': z.object({
  'id': z.string(),
  'version': z.string(),
}),
  'sourceDigest': z.string(),
  'items': z.array(z.object({
  'path': z.string(),
  'action': z.union([z.literal("create"), z.literal("replace"), z.literal("merge")]),
  'conflict': z.union([z.undefined(), z.string()]).optional(),
})),
  'warnings': z.array(z.string()),
})
const dsh_vibe_pack_vibePack_plan_parameter_0$schema = z.union([z.object({
  'kind': z.literal("directory"),
  'path': z.string(),
}), z.object({
  'kind': z.literal("archive"),
  'path': z.string(),
})])
const dsh_vibe_pack_vibePack_plan_result$schema = z.object({
  'pack': z.object({
  'id': z.string(),
  'version': z.string(),
}),
  'sourceDigest': z.string(),
  'items': z.array(z.object({
  'path': z.string(),
  'action': z.union([z.literal("create"), z.literal("replace"), z.literal("merge")]),
  'conflict': z.union([z.undefined(), z.string()]).optional(),
})),
  'warnings': z.array(z.string()),
})
const dsh_vibe_pack_vibePack_uninstall_parameter_0$schema = z.string()
const dsh_vibe_pack_vibePack_uninstall_parameter_1$schema = z.boolean()
const dsh_vibe_pack_vibePack_uninstall_result$schema = z.void()

export const TYPERT = {
  package: 'dsh-vibe-pack',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-vibe-pack#vibePack/diff',
      service: 'vibePack',
      namespace: 'vibePack',
      method: 'diff',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack#vibePack/diff:id',
            schema: dsh_vibe_pack_vibePack_diff_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-vibe-pack#vibePack/diff:result',
        schema: dsh_vibe_pack_vibePack_diff_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-vibe-pack/src/index.ts","line":34,"column":25},
    },
    {
      id: 'dsh-vibe-pack#vibePack/export',
      service: 'vibePack',
      namespace: 'vibePack',
      method: 'export',
      implementation: 'exportPack',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack#vibePack/export:id',
            schema: dsh_vibe_pack_vibePack_export_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-vibe-pack#vibePack/export:result',
        schema: dsh_vibe_pack_vibePack_export_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-vibe-pack/src/index.ts","line":35,"column":27},
    },
    {
      id: 'dsh-vibe-pack#vibePack/history',
      service: 'vibePack',
      namespace: 'vibePack',
      method: 'history',
      implementation: 'historyList',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-vibe-pack/types#PackLedger',
        schema: dsh_vibe_pack_vibePack_history_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-vibe-pack/src/index.ts","line":30,"column":28},
    },
    {
      id: 'dsh-vibe-pack#vibePack/installPack',
      service: 'vibePack',
      namespace: 'vibePack',
      method: 'installPack',
      implementation: 'install',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'source',
          wire: 'source',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack/types#SourceSpec',
            schema: dsh_vibe_pack_vibePack_installPack_parameter_0$schema,
          },
        },
        {
          name: 'force',
          wire: 'force',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack#vibePack/installPack:force',
            schema: dsh_vibe_pack_vibePack_installPack_parameter_1$schema,
          },
        },
        {
          name: 'expectedDigest',
          wire: 'expectedDigest',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack#vibePack/installPack:expectedDigest',
            schema: dsh_vibe_pack_vibePack_installPack_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-vibe-pack/types#InstallPlan',
        schema: dsh_vibe_pack_vibePack_installPack_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-vibe-pack/src/index.ts","line":32,"column":32},
    },
    {
      id: 'dsh-vibe-pack#vibePack/plan',
      service: 'vibePack',
      namespace: 'vibePack',
      method: 'plan',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'source',
          wire: 'source',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack/types#SourceSpec',
            schema: dsh_vibe_pack_vibePack_plan_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-vibe-pack/types#InstallPlan',
        schema: dsh_vibe_pack_vibePack_plan_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-vibe-pack/src/index.ts","line":31,"column":25},
    },
    {
      id: 'dsh-vibe-pack#vibePack/uninstall',
      service: 'vibePack',
      namespace: 'vibePack',
      method: 'uninstall',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack#vibePack/uninstall:id',
            schema: dsh_vibe_pack_vibePack_uninstall_parameter_0$schema,
          },
        },
        {
          name: 'force',
          wire: 'force',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-vibe-pack#vibePack/uninstall:force',
            schema: dsh_vibe_pack_vibePack_uninstall_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-vibe-pack#vibePack/uninstall:result',
        schema: dsh_vibe_pack_vibePack_uninstall_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-vibe-pack/src/index.ts","line":33,"column":30},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote façade. Unknown/non-public DSH resources are deliberately not mutated.",
        "summary": "Remote façade.",
        "tags": [],
        "jsDoc": "/** Remote façade. Unknown/non-public DSH resources are deliberately not mutated. */",
        "key": "vibePack",
        "exportName": "default",
        "members": [
          {
            "kind": "method",
            "name": "historyList",
            "signature": "@Remote('history') async historyList(): Promise<PackLedger>"
          },
          {
            "kind": "method",
            "name": "plan",
            "signature": "@Remote('plan') async plan(source: SourceSpec): Promise<InstallPlan>"
          },
          {
            "kind": "method",
            "name": "install",
            "signature": "@Remote('installPack') async install(source: SourceSpec, force: boolean, expectedDigest: string): Promise<InstallPlan>"
          },
          {
            "kind": "method",
            "name": "uninstall",
            "signature": "@Remote('uninstall') async uninstall(id: string, force: boolean): Promise<void>"
          },
          {
            "kind": "method",
            "name": "diff",
            "signature": "@Remote('diff') async diff(id: string): Promise<Change[]>"
          },
          {
            "kind": "method",
            "name": "exportPack",
            "signature": "@Remote('export') async exportPack(id: string): Promise<string>"
          }
        ],
        "types": [
          {
            "name": "Change",
            "declaration": "export type Change = { type: 'create' | 'update' | 'delete' | 'unchanged'; path: string; before?: FileState; after?: FileState; };"
          },
          {
            "name": "Checkpoint",
            "declaration": "export interface Checkpoint {\n    version: 1;\n    createdAt: string;\n    files: FileState[];\n    ownership: Record<string, string[]>;\n}"
          },
          {
            "name": "FileState",
            "declaration": "export interface FileState {\n    path: string;\n    digest: string;\n    owner?: string;\n}"
          },
          {
            "name": "InstallPlan",
            "declaration": "export type InstallPlan = { pack: Pick<PackV1, 'id' | 'version'>; sourceDigest: string; items: PlanItem[]; warnings: string[]; };"
          },
          {
            "name": "PackLedger",
            "declaration": "export type PackLedger = { version: 1; packs: Record<string, PackLedgerEntry>; };"
          },
          {
            "name": "PackLedgerEntry",
            "declaration": "export type PackLedgerEntry = { version: string; sourceDigest: string; files: Record<string, string>; checkpoint: Checkpoint; };"
          },
          {
            "name": "PackV1",
            "declaration": "export type PackV1 = z.infer<typeof PackSchemaV1>;"
          },
          {
            "name": "PlanItem",
            "declaration": "export type PlanItem = { path: string; action: 'create' | 'replace' | 'merge'; conflict?: string; };"
          },
          {
            "name": "SourceSpec",
            "declaration": "export type SourceSpec = { kind: 'directory'; path: string; } | { kind: 'archive'; path: string; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
