/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { Change, InstallPlan, PackLedger, SourceSpec } from 'dsh-vibe-pack/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$766962655061636b {
    diff: (id: string) => Promise<RemoteResult<Change[]>>
    export: (id: string) => Promise<RemoteResult<string>>
    history: () => Promise<RemoteResult<PackLedger>>
    install: (source: SourceSpec, force: boolean, expectedDigest: string) => Promise<RemoteResult<InstallPlan>>
    plan: (source: SourceSpec) => Promise<RemoteResult<InstallPlan>>
    uninstall: (id: string, force: boolean) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteMap {
    'vibePack/diff': (id: string) => Promise<RemoteResult<Change[]>>
    'vibePack/export': (id: string) => Promise<RemoteResult<string>>
    'vibePack/history': () => Promise<RemoteResult<PackLedger>>
    'vibePack/install': (source: SourceSpec, force: boolean, expectedDigest: string) => Promise<RemoteResult<InstallPlan>>
    'vibePack/plan': (source: SourceSpec) => Promise<RemoteResult<InstallPlan>>
    'vibePack/uninstall': (id: string, force: boolean) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteNamespaceMap {
    'vibePack': TypertRemoteNamespace$766962655061636b
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
